### ISSUE TITLE
Suggestions for further development

### ISSUE THREAD

**Issue by dab3-2014** [AlexIoannides/elasticsearchr#10]
Hi...just read your article at r-bloggers.com and I was elated when I read the title as I was hoping that with this package one can use R to create Kibana & Grafana dashboards. As I understand it, they both rely on the elastic engine, both open-source, and they look stunning! Please take a look at: 
https://www.elastic.co/products/kibana
and
http://grafana.org/

Thanks for the great work, hope to see more of these tools incorporated with R some time in the near future. 

Best,
-Mo Badawy

**Comment by AlexIoannides** [comment]
Thanks for the feedback Mo - greatly appreciated.

I'm a heavy user of Kibana (and I have a little experience with Grafana too). Both of these tools are geared towards creating visualisations (and dashboards), directly from the results of Elasticsearch aggregations.

`elasticsearchr` is a means by which you can get data into Elasticsearch, on which you can then build a Kibana or Grafana visualisations. There is a natural separation of concerns here and I can't (at the moment) see how `elasticsearchr` can help-out with Kibana and Grafana.

What did you have in mind?

**Comment by dab3-2014** [comment]
Hi Alex,
      I have little experience w/ Kibana and Grafana,  but experienced with
R. I think I was simply wondering how easy it would be to use Kibana for
ex. to visualize outputs of R scripts? Maybe in a similar way to Shiny.
Does your new package facilitate such task?

Thanks,
Mo

**Comment by AlexIoannides** [comment]
Yes:
1. use `elasticsearchr` to index data into Elasticsearch (preferably time series data);
2. fire-up Kibana and point it at Elasticsearch; 
3. use the Kibana UI to build visualisations and dashboards; and,
4. share links to your Kibana dashboards or embed then in external web apps, etc.

It isn't any more complicated than that.

Walk-through the Kibana docs here: https://www.elastic.co/guide/en/kibana/current/index.html They're very well written.

**Comment by dab3-2014** [comment]
Awesome!

Thanks.
