### ISSUE TITLE
Data insert error

### ISSUE THREAD

**Issue by logLoss** [AlexIoannides/elasticsearchr#11]
At any time I try to load a big dataframe (1.5GB) into ElasticSearch, I get this error:

Error in httr::content(response)$errors : $ operator is invalid for atomic vectors
In addition: Warning message:
In file.remove(bulk_data_file) :
  cannot remove file 'C:\Users\bxk2\AppData\Local\Temp\RtmpkbNeUp\file234453e121d', reason 'Permission denied'

Smaller datasets works perfectly. I subset the data incrementally and at about 80K rows it falls over.

**Comment by AlexIoannides** [comment]
It's *likely* that you encountering issues with the maximum size of a request to Elasticsearch's bulk API - see https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html#_how_big_is_too_big . I will replicate it on my side to be certain.

Assuming that this is the case, I will provide the ability to handle incremental (or batch) calls to the bulk API from within `elasticsearchr` (this is relatively easy).

**Comment by AlexIoannides** [comment]
This should be fixed by pull-request #12 (on branch 'bulk_bug').

Feel free to test it and let me know if it fixes the issues that you're seeing.
