### ISSUE TITLE
Add support for selecting fields to return from queries

### ISSUE THREAD

**Issue by AlexIoannides** [AlexIoannides/elasticsearchr#13]
This would enable only selected fields to be returned from a query, which would make returning results over http faster when only a subset of the data is required, and avoid having to manually select the required columns on the client side.

In SQL parlance this is equivalent to allowing `SELECT field_1, field_2, ... field_n` as opposed to the current default that is equivalent to `SELECT *`.

In Elasticsearch this is achieved with source filtering - details here: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-get.html#get-source-filtering

**Comment by transmax-open-source** [comment]
Hi there.  Thanks for this library.  We'd be interested in having this as a feature of the project.  Is there anything I can do to assist with it?

**Comment by AlexIoannides** [comment]
Hello.

You're more than welcome to have a go at this yourself and submit a pull request, or if you need this quickly I ought to be able to put something together by the end of next week?

My initial thoughts on how to go about this, would involve implementing another `+` operator (or a `|` operator or suchlike), which embellishes the inner query as outlined [here](https://stackoverflow.com/questions/9605292/make-elasticsearch-only-return-certain-fields#9605566), in much the same way as the `sort_on` works for sorting query results.

**Comment by transmax-open-source** [comment]
Thanks for the reply.  My colleague has put some effort into implementing a solution.  I'll pass your comments on the approach along to him and we'll get a fork ready for your review.

Thanks.

**Comment by hatdropper1977** [comment]
Hey Alex, did you implement this?

**Comment by AlexIoannides** [comment]
Yes - see `select_fields` in the v0.3.0 brach.

So not available on CRAN (yet), but it is there.

**Comment by hatdropper1977** [comment]
Thanks.
Do you have the ability to check if a field  'exists'?
Can you limit the size of the returned number of documents?

**Comment by hatdropper1977** [comment]
Great, thanks!

**Comment by hatdropper1977** [comment]
Hey alex, I downloaded and installed your **v0.3.0** branch of **Elasticsearchr**.  After it compiles, it shows version 0.2.2.999 - no **select_fields** command available.  Do you have v0.3.0 available yet?

**Comment by AlexIoannides** [comment]
That's odd - it is in there, in api.R:

```R
#' Define Elasticsearch query source filter.
#'
#' @export
#'
#' @param json JSON object describing the aggregation that needs to be executed.
#' @return An \code{elastic_source_filter} object.
#'
#' @seealso \url{https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html}
#'
#' @examples
select_fields <- function(json) {
  stopifnot(valid_json(json))
  api_call <- paste0('"_source": ', json)
  structure(list("api_call" = api_call),
            class = c("elastic_source_filter", "elastic_api", "elastic"))
}
```

This is a dev branch and not yet ready for release (CRAN), but I will try and take a look over the weekend.

**Comment by GregSutcliffe** [comment]
I'm seeing this too - RStudio reports 0.3.0 is loaded, but there's no search_fields method available. Is there any progress on getting this released to master? Would be super helpful :P

**Comment by AlexIoannides** [comment]
I should have the time to release it some time in December. I hope that helps.
