### ISSUE TITLE
How can I use "_source" along with Query ?

### ISSUE THREAD

**Issue by rajpaz** [AlexIoannides/elasticsearchr#23]
I want only a subset of fields in the index/documents and my query is something like this 
{
    "_source": [
       "@timestamp","aps.mac","aps.ethMac"
    ], 
"query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": 1488083543485,
                  "lte": 1488084443485,
                  "format": "epoch_millis"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  }
}

I get an error (and most likely because the Query function of elasticsearchr does not like the "_source" filter.  Is there a workaround ? 

thanks

**Comment by AlexIoannides** [comment]
#13 cover this use case and with any luck I'll be able to re-start development in March.
