### ISSUE TITLE
size parameter not being shown in print

### ISSUE THREAD

**Issue by brianolsen87** [AlexIoannides/elasticsearchr#27]
Hi Alex, 

First I wanted to say thanks, you've done a great job with this library. I'm finding it to be exactly what I need to prototype a few ideas without having to hassle too much with logstash to mutate and move my data. 

Just a very small issue. It seems when setting the size, when I print I am not seeing the size in the output. This doesn't affect the actual query itself but wanted to report it anyways.

`my_small_query <- query('{
  "match_all": {}
}', 10)
`

` print(my_small_query)`

> {
>     "query": {
>         "match_all": {
> 
>         }
>     }
> }

`print(my_small_query + avg_sepal_width)`

> {
>     "size": 0,
>     "query": {
>         "match_all": {
>
>         }
>     },
>     "aggs": {
>         "avg_sepal_width_per_species": {
>             "terms": {
>                 "field": "species",
>                 "size": 3
>             },
>             "aggs": {
>                 "avg_sepal_width": {
>                     "avg": {
>                         "field": "sepal_width"
>                     }
>                 }
>             }
>         }
>     }
> }

looking at the source: 

> query <- function(json, size = 0) {
> 
>   stopifnot(valid_json(json))
>   api_call <- paste0('"query":', json)
>   structure(list("api_call" = api_call, "size" = size),
>             class = c("elastic_query", "elastic_api", "elastic"))
> }

You are actually setting it, but it was just a bit confusing starting out. 

Thanks!

**Comment by brianolsen87** [comment]
Another question, if we were to run `results = es %search% (my_small_query + avg_sepal_width)` will the size affect the results at all or will it always be set to 0? Perhaps this is being done intentionally for simplicity of not having to separate hits/aggs?

**Comment by AlexIoannides** [comment]
Hi Brian, 

Firstly, my apologies for the tardy reply - I'm having one hell of a year...

When running an aggregation, the high-level `size` parameter is automatically set to `0`. The decision behind this, is that when running an aggregation my personal preference is not to get any query results back with my aggregation results.

With respect to the printing of `size` in a query, then you're correct - it has been unintentionally left out of the printed output and ought to be corrected.

Many thanks,

Alex

**Comment by AlexIoannides** [comment]
This has been fixed in v0.2.1 that has been submitted to CRAN.

I'm sorry this took so long.

**Comment by brianolsen87** [comment]
Thanks! No problem, this wasn't a show stopper.
