### ISSUE TITLE
Option to turn off cleaned_field_names() in indexing not Present

### ISSUE THREAD

**Issue by bkm009** [AlexIoannides/elasticsearchr#34]
Hello,

For some reason I need the column headers case same as I am giving in dataframe. I went through the code in api.R (line no. 175) , and I seen that for indexing cleaned_field_names() this operation is performed. 

I think you must give user option to use this method or not based upon his choice. Your concern is that column names must be in proper format and that is fine, and in the case ES Server rejects the column headers , you can throw an error to user back.

I hope you will think on it.

**Comment by AlexIoannides** [comment]
Hello,

If you take a look at the code for `cleaned_field_names()` in the utils.R file, you'll see that all this function does is to replaces periods underscores - i.e. `.` with `_`. This is necessary as the periods have a special meaning in Elasticsearch (i.e. they refer to fields in nested objects). 

I don't see how or why this should be optional - can you elaborate on your use-case in a bit more detail and provide an actual example, please?
