### ISSUE TITLE
Feature Request:  R-Studio 'New Connection' Integration(Wizard)

### ISSUE THREAD

**Issue by hatdropper1977** [AlexIoannides/elasticsearchr#37]
Thank you for developing this great product.

I have a silly request... I think it would be neat to be able to connect to an ES database using the R-Studio connection GUI.  R-Studio - Hadoop, Microsoft, etc. all have wizards to make connections via the GUI.

Again - not critical, but to me it would be 'fun.'  Thanks agan!

**Comment by AlexIoannides** [comment]
I know what you mean, but I don't have the motivation to code one as time is limited and there are other (far more basic) priorities for this project.

You're more than welcome to have a go yourself and submit a pull request.
