### ISSUE TITLE
support for authentication?

### ISSUE THREAD

**Issue by johnjfox** [AlexIoannides/elasticsearchr#39]
I'm sure I'm missing it, but how do I add username / password fo, for example, I can connect to an elastic cloud based instance?

**Comment by AlexIoannides** [comment]
I don't have any experience with ElasticCloud - how are you connect at the moment?

**Comment by hatdropper1977** [comment]
Try this:

```json
match_all_query <- query('{
                    "match_all": {}
                    }')
```

And then:
```R
elastic('https://your_username:your_password@ec47fc4d2c53414e1307e85726d4b9bb.us-east-1.aws.found.io:9243', your_index) %search% (match_all_query)
```

Replace the above example with your ES cloud API address and your username, password and index name.  NOTE:  Elastic 6.X does not support document types.

**Comment by johnjfox** [comment]
Thanks!!!! I’ll try that

**Comment by hatdropper1977** [comment]
@johnjfox  - Hove you tried to CURL your endpoint from the command line?  What URL do you use?
