### ISSUE TITLE
How can I install version 0.3.0

### ISSUE THREAD

**Issue by fissehab** [AlexIoannides/elasticsearchr#40]
I want to take advantage of the new enhancements in version 0.3.0 such as getting only selected fields rather than all of them and I have to install version 0.3.0 to do that but the line of code below installs version 0.2.0 which does not do what I mentioned above. How can I install version 0.3.0?
devtools::install_github("alexioannides/elasticsearchr")

**Comment by hatdropper1977** [comment]
@fissehab check out this link, section 3.1.1https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html.  you'll want to set the ref to v0.3.0.

**Comment by fissehab** [comment]
Thank you!
