### ISSUE TITLE
Update (overwrite) action causes node failure in parallel

### ISSUE THREAD

**Issue by 1beb** [AlexIoannides/elasticsearchr#44]
I'm working with a rather large data set where I have to test equality and update it. I do this in a parallel process. However, anytime it happens upon a record that already exists, it crashes the node (and ends the process) 

Here's some repro code for you: 

```
doc = data.frame(id = 1:100, text = rep("Hello!", 100))

update_fun = function(doc) { 
  res = elastic("ip", "some", "thing") 
  res %index% doc
}
# populate
l = foreach(i = 1:100, .packages = "elasticsearchr") %dopar% { 
  update_fun(doc[i,])
}

# attempt update 
l = foreach(i = 1:100, .packages = "elasticsearchr") %dopar% { 
  update_fun(doc[i,])
}
```

The ELK server is pretty hefty (4cpu/8gb) and the docs are pretty small so I kind of expect a few hundred ops / sec should be breezy. 

Any thoughts on what could be going on?

- could be related to connections (unclosed)

**Comment by 1beb** [comment]
I just noticed that even when a cluster is active, you can crash the sockets simply by calling %index% on already existing ids but not even working from within the context of the cluster.

**Comment by AlexIoannides** [comment]
Do you experience the same issue when using Elasticsearch's native REST API to update a document?

**Comment by 1beb** [comment]
I don't know how to test that. Do you have an example. The above example continues to fail in parallel SNOW cluster.

**Comment by 1beb** [comment]
I can confirm that this doesn't happen during a query, nor a delete action, but only during an index action. I was looking at your code and there's nothing that jumps out at me other than that you're not importing utils package.

**Comment by AlexIoannides** [comment]
See [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docs.html) for information on Elasticsearch's REST API.

Some questions:

1. what version of Elasticsearch are you running?
2. what error message are you getting?
3. do you still get the error when not running in parallel?
4. what's a "_... parallel SNOW cluster_"? And, potentially how many parallel requests could it send to your cluster?
5. if you were to use an HTTP client (e.g. `httr`) and the native REST APIs for indexing and updating, as opposed to `elasticsearchr`, does it work?

**Comment by 1beb** [comment]
Another interesting finding. Even outside of `foreach` loop, an %index% operation crashes all the workers.

**Comment by 1beb** [comment]
Here's an psuedo-example that you can setup for yourself: 

```
library(parallel)
library(foreach)
library(doSNOW)
library(elasticsearchr) 

cpus = detectCores() - 2
cl = makeCluster(cpus, outfile = "cluster-log.txt")
registerDoSNOW(cl)

res = elasticsearchr("your_es", "data", "data")
res %index% iris

# All nodes crash immediately
```

**Comment by 1beb** [comment]
@AlexIoannides No problem, we can leave this one closed. I don't think the problem/solution is going to easily identified.

For passerby, my solution was to index at the end, instead of the middle of my process. `%index%` handles rather large pushes well and quickly, so I saved data in chunks (I/O to serialized RDS) during my process then sequentially looped over my chunks to upload them to elasticsearch.
