### ISSUE TITLE
README mentions select_fields but it doesn't appear in package

### ISSUE THREAD

**Issue by Ploulackk** [AlexIoannides/elasticsearchr#48]
hello,
Thank you for your work, hello from Sweden.

I'm starting on ElasticSearch (new to a company that's fairly new itself and wants to base its analytics - games - on it).
I'm just confused that your Readme refers to a function I'm not seeing in the package list of functions.
And since your 'query' function is, well, a query, I wouldn't know where to add the "_source" (it's the only I've understood so far on how to select fields on the query).

**Comment by Ploulackk** [comment]
My bad. I was on the CRAN version I guess. After pulling from here, it's fine. As I said...noob :)

**Comment by AlexIoannides** [comment]
No problem :-)
