### ISSUE TITLE
Unable to index data

### ISSUE THREAD

**Issue by FinScience** [AlexIoannides/elasticsearchr#50]
Hi,

While trying to replicate the example of indexing iris data into elastic, RStudio throws an exception.

![image](https://user-images.githubusercontent.com/11004504/55051170-10d2e680-507a-11e9-9130-ff7d3d89b414.png)

Any help with this would be great

**Comment by AlexIoannides** [comment]
Looks like you cluster is timing-out for some reason and that the problem resides there.
