### ISSUE TITLE
Fetch data in elastic take lot of time

### ISSUE THREAD

**Issue by amoussoubaruch** [AlexIoannides/elasticsearchr#51]
Hi, 

I'm starting use this elastic client to extract data and process it with R. 
My index have more than 50Gb size. I use R to send query to get some data. 
It's take very long time to have data in a R dataframe. 
Can i have possibility to increase this performance? 

Thanks in advanced

**Comment by AlexIoannides** [comment]
Try selecting only the columns you need to return (to minimise the volume of data your need returned), via the `select_fields` method. Also, have you benchmarked your query using the native REST API to get an idea of how much your cluster itself may be the bottleneck?

**Comment by amoussoubaruch** [comment]
Thanks Alex for your reply. 
My query work well now. The problem is that i try to get a large data with R. 
After using filter, select_field and aggregation it's run very fast. Compare to native REST API i just have less difference in time processing.
