### ISSUE TITLE
add update method

### ISSUE THREAD

**Issue by dfalbel** [AlexIoannides/elasticsearchr#9]
Thanks! Very nice  package!!

It would be useful to be able to update documents as described here.

https://www.elastic.co/guide/en/elasticsearch/reference/current/_updating_documents.html#_updating_documents

**Comment by AlexIoannides** [comment]
Thanks Daniel!

From the top of the link you posted,

> _"Note though that Elasticsearch does not actually do in-place updates under the hood. Whenever we do an update, Elasticsearch deletes the old document and then indexes a new document with the update applied to it in one shot."_

With this in mind, if we index a document using,

```r
# index document original document
elastic("http://localhost:9200", "github", "issues") %index% 
  data.frame("id" = 1, "name" = "Daniel", "type" = "feature request")

# retrieve document from Elasticsearch
elastic("http://localhost:9200", "github", "issues") %search% 
  query('{"match_all": {}}')

#  ...  id   name            type
#  1     1 Daniel feature request
```

We can then 'update' it by doing,

```r
# update document by re-indexing
elastic("http://localhost:9200", "github", "issues") %index% 
  data.frame("id" = 1, "name" = "Daniel Falbel", "type" = "enhancement")

# retrieve document from Elasticsearch
elastic("http://localhost:9200", "github", "issues") %search% 
  query('{"match_all": {}}')

#  ...  id          name        type
#     1  1 Daniel Falbel enhancement
```

Does this cover your use case?

**Comment by dfalbel** [comment]
This works... But if I want to update only the `type`  for a document I will need to query the full document, and then update only the `type` field, for example?

**Comment by AlexIoannides** [comment]
Ah, yes - I understand now, you're after partial document updates.

**Comment by dfalbel** [comment]
Exactly! I don't know if this is possible, but it would be a good functionality.

**Comment by AlexIoannides** [comment]
It is possible and I will include it in the next version.

**Comment by 1beb** [comment]
Just to be clear. There's no need to %delete% and then %index%. If you index with an id specified the beahviour is like "overwrite"? Is that correct?
